### ISSUE TITLE
Negative vote counts sometimes

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#1824]
Post https://www.lesswrong.com/posts/nTDQ9eNrSNoYrZzJw/would-solving-logical-counterfactuals-solve-anthropics somehow ended up with a negative vote count. Given when the post was created, the problem is not the result of an import or migration script. We should figure out how that happened.

**Comment by jimrandomh** [comment]
Relatedly, we sometimes get race-conditiony-looking duplicate votes. See for example `g5TeNYrktgd3AL4Wn`. The first duplicated vote on that document is two unvotes on the same vote, which is followed by two strong-upvotes..

**Comment by jimrandomh** [comment]
Possibly fixed by https://github.com/LessWrong2/Lesswrong2/pull/1873 , but uncertain about it.

**Comment by mateon1** [comment]
This is not fixed, see: https://www.lesswrong.com/posts/tMhEv28KJYWsu6Wdo/kensh?commentId=PAAWL9ZEBFGe8yNkS
I believe the original score was 2 (or maybe 3) karma, 2 votes, now it's 8 karma, -3 votes.
I tried to fix this by un-voting, but the UI is behaving in a very buggy manner, and I believe I accidentally worsened the situation and generated karma from thin air...
